FROM openjdk:8-jdk-alpine

MAINTAINER liubiao "2691973894@qq.com"

WORKDIR /jar
ENV PATH /usr/local/bin:$PATH

VOLUME /jar

RUN mkdir -p /jar/logs

COPY ../ruoyi-modules/ruoyi-workflow/target/ruoyi-modules-workflow.jar /jar/app.jar

EXPOSE 9400

ENV TZ=Asia/Shanghai

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/jar/app.jar"]